### ISSUE TITLE
"Implementation" incorrectly detected as spelling error

### ISSUE THREAD

**Issue by britter** [jsoref/spelling#1]
Hello,

your PR to [Commons Jelly](https://github.com/apache/commons-jelly/pull/1) changed incorrectly changed all occurrences of "Implementation" to "Implementstion". This looks like a bug in your spelling tool.

**Comment by jsoref** [comment]
Thanks, that wasn't a bug in the tool, it was human error.


I ran:
```
rs Implementa Implements
```
To fix [Implementa](https://github.com/apache/commons-jelly/commit/4774194b54fdc6b64d03717a606a993fc7334f2f#diff-b5547fff31ec29ebc0cbb06f8ea3a448
):
>        <li>Implementa a META-INF/services mechanism for mapping Jelly libraries to namespace URIs
And I didn't correctly review the resulting diff (`d -c .`), nor did I rerun `f` to confirm that I hadn't introduced any spelling mistakes.

A safer/more correct command would have been:
```
rs 'Implementa a' 'Implements a' implements
```

Sorry about that.
