### ISSUE TITLE
keys on reference is experimental

### ISSUE THREAD

**Issue by romani** [jsoref/spelling#6]
https://github.com/jsoref/spelling/blob/master/w

result:
```
keys on reference is experimental at /checkstyle/checkstyle/.ci-temp/contribution/jsoref-spellchecker/spelling-unknown-word-splitter.pl line 37.
keys on reference is experimental at /checkstyle/checkstyle/.ci-temp/contribution/jsoref-spellchecker/spelling-unknown-word-splitter.pl line 52.
keys on reference is experimental at /checkstyle/checkstyle/.ci-temp/contribution/jsoref-spellchecker/spelling-unknown-word-splitter.pl line 79.
```

is https://stackoverflow.com/a/29614053/1015848 a fix ?

**Comment by jsoref** [comment]
Yes, I think it is. I have some vague recollection of hitting that somewhere and making exactly that change (probably based on that StackOverflow item).

**Comment by jsoref** [comment]
Sorry, fixed by: https://github.com/jsoref/spelling/commit/5c30a469329e7a4a9083e70208e6006af358d5fd
